const menu = [
  {
    id: 1,
    title: 'Title 1',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 2,
    title: 'Title 2',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 3,
    title: 'Title 3',
    category: 'drink',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 4,
    title: 'Title 4',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 5,
    title: 'Title 5',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 6,
    title: 'Title 6',
    category: 'drink',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 7,
    title: 'Title 7',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 8,
    title: 'Title 8',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
  {
    id: 9,
    title: 'Title 9',
    category: 'drink',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
  },
];

export default menu;
